apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-app
  template:
    metadata:
      labels:
        app: fullstack-app
    spec:
      containers:
        - name: fullstack-app
          image: yash6163/fullstack-app:latest
          ports:
            - containerPort: 3000